### ISSUE TITLE
Feature Request: Specify job(s) to wait for

### ISSUE THREAD

**Issue by m-roberts** [kachick/wait-other-jobs#474]
It would be great to have the option to only need to wait for a subset of all other jobs, rather than having to wait for all jobs.

**Comment by kachick** [comment]
Sorry for being late around this issue, the implementation was a bit hard for me. 🙇‍♂️ 

I have released v2, that includes this feature. https://github.com/kachick/wait-other-jobs/releases/tag/v2.0.0
If you still have the interest, trying with it and feedback helps me a lot!
