### ISSUE TITLE
[Question]: initial polling delay might be implemented differently

### ISSUE THREAD

**Issue by Yehonal** [kachick/wait-other-jobs#820]
### What happened?

Hello, thanks for this action!

## Problem

I'm using it for a monorepo to wait for the deployment of the core infra resources before deploying the applications. However, the job I have to wait for, it runs after 40-50 seconds when we don't have cache hitting on the previous job that is installing the dependencies. Otherwise, it runs after 5 seconds.

However, to make it work I had to set this `wait-seconds-before-first-polling: '40'`, which is needed because in the first 40 seconds the job doesn't exist yet, so it works well with the first condition. But for the second (cache hit), we are wasting 40 seconds since the job we are waiting is actually already completed.

## Possible solutions

* Polling while waiting and exit the waiting timer early if the job is in progress
* Find an alternative way to the waiting system before polling 

### Version

v3.2.0

### Permissions

  Actions: read
  Checks: read
  Contents: read
  Metadata: read

### Parameters

      - name: Wait for infra core deployment
        uses: kachick/wait-other-jobs@v3.2.0
        timeout-minutes: 15 # Recommended to be enabled with your appropriate value for fail-safe use
        with:
          wait-seconds-before-first-polling: '40'
          min-interval-seconds: '10'
          retry-method: 'equal_intervals'
          early-exit: 'true'
          skip-same-workflow: 'false'
          wait-list: |
            [
              {
                "workflowFile": "infra-api.yml",
                "jobName": "CI/CD Infra Core CDK / CDK CD",
                "optional": false
              }
            ]

### Relevant log output

```shell
no logs
```

**Comment by kachick** [comment]
Thanks for creating this issue!
As I understand it, this is similar to or related to a known limitation as written in https://github.com/kachick/wait-other-jobs/blob/47f7c49f67d8d9bb05d8040adbee7b3caaf11e02/README.md#L120-L124.

But I noticed using wait-list may resolve it, so implemented the feature in GH-821

I'll release it with some other changes. 🙏

**Comment by Yehonal** [comment]
That was fast! Thank you! I will test it soon

**Comment by kachick** [comment]
Released with https://github.com/kachick/wait-other-jobs/releases/tag/v3.3.0 🚀

**Comment by Yehonal** [comment]
Test and it works for me! Thanks again!
